version: '3.1'
services:
  mysql:
    image: mysql:8.0.31
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mobile
    command: --default-authentication-plugin=mysql_native_password
    restart: always
  
  api:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      DB_HOST: mysql
      DB_PASS: password
      DB_NAME: mobile
      DB_USER: root
      JWT_SECRET: ${JWT_SECRET}
      PORT: '9090'
    restart: always
    depends_on: [mysql]
    ports:
      - 9090:9090